// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.revrobotics.CANSparkMax; 
import com.revrobotics.CANSparkMaxLowLevel.MotorType;
import edu.wpi.first.wpilibj.DigitalInput;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class HorizontalElevator extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private CANSparkMax cANSparkMAXH1;
private CANSparkMax cANSparkMAXH2;
private CANSparkMax cANSparkMAXHR;
private DigitalInput hElimitExtended;
private DigitalInput hELimitRetracted;
private DigitalInput hRLimitRetracted;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    /**
    *
    */
    public HorizontalElevator() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
cANSparkMAXH1 = new CANSparkMax(8, MotorType.kBrushless);
 
 

cANSparkMAXH2 = new CANSparkMax(9, MotorType.kBrushless);
 
 

cANSparkMAXHR = new CANSparkMax(10, MotorType.kBrushless);
 
 

hElimitExtended = new DigitalInput(2);
 addChild("HElimitExtended", hElimitExtended);
 

hELimitRetracted = new DigitalInput(3);
 addChild("HELimitRetracted", hELimitRetracted);
 

hRLimitRetracted = new DigitalInput(4);
 addChild("HRLimitRetracted", hRLimitRetracted);
 


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    cANSparkMAXH2.follow(cANSparkMAXH1);
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void HEExtend(){
        cANSparkMAXH1.set(0.5);
    }

    public void HERetract(){
        cANSparkMAXH1.set(-0.5);
    }

    public void HEStop(){
        cANSparkMAXH1.set(0);
    }

    public void HRUp(){
        cANSparkMAXHR.set(0.5);
    }

    public void HRDown(){
        cANSparkMAXHR.set(0.5);
    }

    public void HRStop(){
        cANSparkMAXHR.set(0);
    }

}

